/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.kakfainaction;

import org.apache.avro.specific.SpecificData;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class Alert extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 5295476477295037008L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"Alert\",\"namespace\":\"com.kakfainaction\",\"fields\":[{\"name\":\"sensor_id\",\"type\":\"long\",\"doc\":\"The unique id that identifies the sensor\"},{\"name\":\"stage_id\",\"type\":\"string\",\"doc\":\"The unique id that identifies the stage\"},{\"name\":\"stage_reason\",\"type\":\"string\",\"doc\":\"The unique id that identifies the stage\"},{\"name\":\"time\",\"type\":\"long\",\"doc\":\"Time the alert was generated as UTC milliseconds from the epoch\"},{\"name\":\"status\",\"type\":{\"type\":\"enum\",\"name\":\"alert_status\",\"symbols\":[\"Critical\",\"Major\",\"Minor\",\"Warning\"]},\"doc\":\"The allowed values that our sensors will use to emit current status\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<Alert> ENCODER =
      new BinaryMessageEncoder<Alert>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<Alert> DECODER =
      new BinaryMessageDecoder<Alert>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   */
  public static BinaryMessageDecoder<Alert> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   */
  public static BinaryMessageDecoder<Alert> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<Alert>(MODEL$, SCHEMA$, resolver);
  }

  /** Serializes this Alert to a ByteBuffer. */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /** Deserializes a Alert from a ByteBuffer. */
  public static Alert fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  /** The unique id that identifies the sensor */
  @Deprecated public long sensor_id;
  /** The unique id that identifies the stage */
  @Deprecated public java.lang.CharSequence stage_id;
  /** The unique id that identifies the stage */
  @Deprecated public java.lang.CharSequence stage_reason;
  /** Time the alert was generated as UTC milliseconds from the epoch */
  @Deprecated public long time;
  /** The allowed values that our sensors will use to emit current status */
  @Deprecated public com.kakfainaction.alert_status status;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public Alert() {}

  /**
   * All-args constructor.
   * @param sensor_id The unique id that identifies the sensor
   * @param stage_id The unique id that identifies the stage
   * @param stage_reason The unique id that identifies the stage
   * @param time Time the alert was generated as UTC milliseconds from the epoch
   * @param status The allowed values that our sensors will use to emit current status
   */
  public Alert(java.lang.Long sensor_id, java.lang.CharSequence stage_id, java.lang.CharSequence stage_reason, java.lang.Long time, com.kakfainaction.alert_status status) {
    this.sensor_id = sensor_id;
    this.stage_id = stage_id;
    this.stage_reason = stage_reason;
    this.time = time;
    this.status = status;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return sensor_id;
    case 1: return stage_id;
    case 2: return stage_reason;
    case 3: return time;
    case 4: return status;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: sensor_id = (java.lang.Long)value$; break;
    case 1: stage_id = (java.lang.CharSequence)value$; break;
    case 2: stage_reason = (java.lang.CharSequence)value$; break;
    case 3: time = (java.lang.Long)value$; break;
    case 4: status = (com.kakfainaction.alert_status)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'sensor_id' field.
   * @return The unique id that identifies the sensor
   */
  public java.lang.Long getSensorId() {
    return sensor_id;
  }

  /**
   * Sets the value of the 'sensor_id' field.
   * The unique id that identifies the sensor
   * @param value the value to set.
   */
  public void setSensorId(java.lang.Long value) {
    this.sensor_id = value;
  }

  /**
   * Gets the value of the 'stage_id' field.
   * @return The unique id that identifies the stage
   */
  public java.lang.CharSequence getStageId() {
    return stage_id;
  }

  /**
   * Sets the value of the 'stage_id' field.
   * The unique id that identifies the stage
   * @param value the value to set.
   */
  public void setStageId(java.lang.CharSequence value) {
    this.stage_id = value;
  }

  /**
   * Gets the value of the 'stage_reason' field.
   * @return The unique id that identifies the stage
   */
  public java.lang.CharSequence getStageReason() {
    return stage_reason;
  }

  /**
   * Sets the value of the 'stage_reason' field.
   * The unique id that identifies the stage
   * @param value the value to set.
   */
  public void setStageReason(java.lang.CharSequence value) {
    this.stage_reason = value;
  }

  /**
   * Gets the value of the 'time' field.
   * @return Time the alert was generated as UTC milliseconds from the epoch
   */
  public java.lang.Long getTime() {
    return time;
  }

  /**
   * Sets the value of the 'time' field.
   * Time the alert was generated as UTC milliseconds from the epoch
   * @param value the value to set.
   */
  public void setTime(java.lang.Long value) {
    this.time = value;
  }

  /**
   * Gets the value of the 'status' field.
   * @return The allowed values that our sensors will use to emit current status
   */
  public com.kakfainaction.alert_status getStatus() {
    return status;
  }

  /**
   * Sets the value of the 'status' field.
   * The allowed values that our sensors will use to emit current status
   * @param value the value to set.
   */
  public void setStatus(com.kakfainaction.alert_status value) {
    this.status = value;
  }

  /**
   * Creates a new Alert RecordBuilder.
   * @return A new Alert RecordBuilder
   */
  public static com.kakfainaction.Alert.Builder newBuilder() {
    return new com.kakfainaction.Alert.Builder();
  }

  /**
   * Creates a new Alert RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new Alert RecordBuilder
   */
  public static com.kakfainaction.Alert.Builder newBuilder(com.kakfainaction.Alert.Builder other) {
    return new com.kakfainaction.Alert.Builder(other);
  }

  /**
   * Creates a new Alert RecordBuilder by copying an existing Alert instance.
   * @param other The existing instance to copy.
   * @return A new Alert RecordBuilder
   */
  public static com.kakfainaction.Alert.Builder newBuilder(com.kakfainaction.Alert other) {
    return new com.kakfainaction.Alert.Builder(other);
  }

  /**
   * RecordBuilder for Alert instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<Alert>
    implements org.apache.avro.data.RecordBuilder<Alert> {

    /** The unique id that identifies the sensor */
    private long sensor_id;
    /** The unique id that identifies the stage */
    private java.lang.CharSequence stage_id;
    /** The unique id that identifies the stage */
    private java.lang.CharSequence stage_reason;
    /** Time the alert was generated as UTC milliseconds from the epoch */
    private long time;
    /** The allowed values that our sensors will use to emit current status */
    private com.kakfainaction.alert_status status;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.kakfainaction.Alert.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.sensor_id)) {
        this.sensor_id = data().deepCopy(fields()[0].schema(), other.sensor_id);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.stage_id)) {
        this.stage_id = data().deepCopy(fields()[1].schema(), other.stage_id);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.stage_reason)) {
        this.stage_reason = data().deepCopy(fields()[2].schema(), other.stage_reason);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.time)) {
        this.time = data().deepCopy(fields()[3].schema(), other.time);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.status)) {
        this.status = data().deepCopy(fields()[4].schema(), other.status);
        fieldSetFlags()[4] = true;
      }
    }

    /**
     * Creates a Builder by copying an existing Alert instance
     * @param other The existing instance to copy.
     */
    private Builder(com.kakfainaction.Alert other) {
            super(SCHEMA$);
      if (isValidValue(fields()[0], other.sensor_id)) {
        this.sensor_id = data().deepCopy(fields()[0].schema(), other.sensor_id);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.stage_id)) {
        this.stage_id = data().deepCopy(fields()[1].schema(), other.stage_id);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.stage_reason)) {
        this.stage_reason = data().deepCopy(fields()[2].schema(), other.stage_reason);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.time)) {
        this.time = data().deepCopy(fields()[3].schema(), other.time);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.status)) {
        this.status = data().deepCopy(fields()[4].schema(), other.status);
        fieldSetFlags()[4] = true;
      }
    }

    /**
      * Gets the value of the 'sensor_id' field.
      * The unique id that identifies the sensor
      * @return The value.
      */
    public java.lang.Long getSensorId() {
      return sensor_id;
    }

    /**
      * Sets the value of the 'sensor_id' field.
      * The unique id that identifies the sensor
      * @param value The value of 'sensor_id'.
      * @return This builder.
      */
    public com.kakfainaction.Alert.Builder setSensorId(long value) {
      validate(fields()[0], value);
      this.sensor_id = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'sensor_id' field has been set.
      * The unique id that identifies the sensor
      * @return True if the 'sensor_id' field has been set, false otherwise.
      */
    public boolean hasSensorId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'sensor_id' field.
      * The unique id that identifies the sensor
      * @return This builder.
      */
    public com.kakfainaction.Alert.Builder clearSensorId() {
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'stage_id' field.
      * The unique id that identifies the stage
      * @return The value.
      */
    public java.lang.CharSequence getStageId() {
      return stage_id;
    }

    /**
      * Sets the value of the 'stage_id' field.
      * The unique id that identifies the stage
      * @param value The value of 'stage_id'.
      * @return This builder.
      */
    public com.kakfainaction.Alert.Builder setStageId(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.stage_id = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'stage_id' field has been set.
      * The unique id that identifies the stage
      * @return True if the 'stage_id' field has been set, false otherwise.
      */
    public boolean hasStageId() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'stage_id' field.
      * The unique id that identifies the stage
      * @return This builder.
      */
    public com.kakfainaction.Alert.Builder clearStageId() {
      stage_id = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'stage_reason' field.
      * The unique id that identifies the stage
      * @return The value.
      */
    public java.lang.CharSequence getStageReason() {
      return stage_reason;
    }

    /**
      * Sets the value of the 'stage_reason' field.
      * The unique id that identifies the stage
      * @param value The value of 'stage_reason'.
      * @return This builder.
      */
    public com.kakfainaction.Alert.Builder setStageReason(java.lang.CharSequence value) {
      validate(fields()[2], value);
      this.stage_reason = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'stage_reason' field has been set.
      * The unique id that identifies the stage
      * @return True if the 'stage_reason' field has been set, false otherwise.
      */
    public boolean hasStageReason() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'stage_reason' field.
      * The unique id that identifies the stage
      * @return This builder.
      */
    public com.kakfainaction.Alert.Builder clearStageReason() {
      stage_reason = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'time' field.
      * Time the alert was generated as UTC milliseconds from the epoch
      * @return The value.
      */
    public java.lang.Long getTime() {
      return time;
    }

    /**
      * Sets the value of the 'time' field.
      * Time the alert was generated as UTC milliseconds from the epoch
      * @param value The value of 'time'.
      * @return This builder.
      */
    public com.kakfainaction.Alert.Builder setTime(long value) {
      validate(fields()[3], value);
      this.time = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'time' field has been set.
      * Time the alert was generated as UTC milliseconds from the epoch
      * @return True if the 'time' field has been set, false otherwise.
      */
    public boolean hasTime() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'time' field.
      * Time the alert was generated as UTC milliseconds from the epoch
      * @return This builder.
      */
    public com.kakfainaction.Alert.Builder clearTime() {
      fieldSetFlags()[3] = false;
      return this;
    }

    /**
      * Gets the value of the 'status' field.
      * The allowed values that our sensors will use to emit current status
      * @return The value.
      */
    public com.kakfainaction.alert_status getStatus() {
      return status;
    }

    /**
      * Sets the value of the 'status' field.
      * The allowed values that our sensors will use to emit current status
      * @param value The value of 'status'.
      * @return This builder.
      */
    public com.kakfainaction.Alert.Builder setStatus(com.kakfainaction.alert_status value) {
      validate(fields()[4], value);
      this.status = value;
      fieldSetFlags()[4] = true;
      return this;
    }

    /**
      * Checks whether the 'status' field has been set.
      * The allowed values that our sensors will use to emit current status
      * @return True if the 'status' field has been set, false otherwise.
      */
    public boolean hasStatus() {
      return fieldSetFlags()[4];
    }


    /**
      * Clears the value of the 'status' field.
      * The allowed values that our sensors will use to emit current status
      * @return This builder.
      */
    public com.kakfainaction.Alert.Builder clearStatus() {
      status = null;
      fieldSetFlags()[4] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public Alert build() {
      try {
        Alert record = new Alert();
        record.sensor_id = fieldSetFlags()[0] ? this.sensor_id : (java.lang.Long) defaultValue(fields()[0]);
        record.stage_id = fieldSetFlags()[1] ? this.stage_id : (java.lang.CharSequence) defaultValue(fields()[1]);
        record.stage_reason = fieldSetFlags()[2] ? this.stage_reason : (java.lang.CharSequence) defaultValue(fields()[2]);
        record.time = fieldSetFlags()[3] ? this.time : (java.lang.Long) defaultValue(fields()[3]);
        record.status = fieldSetFlags()[4] ? this.status : (com.kakfainaction.alert_status) defaultValue(fields()[4]);
        return record;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<Alert>
    WRITER$ = (org.apache.avro.io.DatumWriter<Alert>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<Alert>
    READER$ = (org.apache.avro.io.DatumReader<Alert>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}
